# Generated by Django 4.0.6 on 2022-09-22 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learneranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='learneranswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='learner',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='quiz',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='interest',
            new_name='interests',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='quizzes',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='LearnerAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
    ]
